table citas_hechos
	lineageTag: ee63b444-457b-43a3-a9e6-f19c8493c83c

	measure 'Total de citas' = COUNT('citas_hechos'[id_cita])
		formatString: 0
		lineageTag: 94699ce3-2c4a-4731-9349-9401320365ca

	measure 'Citas Canceladas' = ```
			CALCULATE(
			    COUNT(citas_hechos[id_cita]), 
			    citas_hechos[estado_cita] = "Cancelada"
			)
			```
		formatString: 0
		lineageTag: f6b061b7-cd50-445b-a663-ed1df2a960b0

	measure 'Citas Reprogramadas' = ```
			
			CALCULATE(
			    COUNT(citas_hechos[id_cita]), 
			    citas_hechos[estado_cita] = "Reprogramada"
			)
			```
		formatString: 0
		lineageTag: 5ed5c102-0e02-45c9-92c8-79acd20418dd

	measure 'Citas programadas' = ```
			
			CALCULATE(
			    COUNT(citas_hechos[id_cita]), 
			    citas_hechos[estado_cita] = "Programada"
			)
			```
		formatString: 0
		lineageTag: e6c1829a-2ac5-4a47-b7ce-ac9875f14786

	measure 'Citas Atendidas' = ```
			CALCULATE(
			    COUNT(citas_hechos[id_cita]), 
			    citas_hechos[estado_cita] = "Atendida"
			)
			```
		formatString: 0
		lineageTag: be7da173-4c21-4ff7-80da-c357ff419fa1

	measure 'Tasa de Atención' =
			
			DIVIDE(
			    [Citas Atendidas],
			    [Total de citas],
			    0
			)
		lineageTag: cc94bac0-5bae-48f0-88a6-6c20b97e962c

	measure 'Tasa de cancelacion' =
			DIVIDE(
			    [Citas Canceladas],
			    [Total de citas],
			    0
			)
		lineageTag: 4c4d64bc-1ae6-4f0a-9ee6-4e142bdb2ca6

	measure 'Tasa de programacion' =
			DIVIDE(
			    [Citas programadas],
			    [Total de citas],
			    0
			)
		lineageTag: de731e72-e372-45e1-b06d-704f8dd27c0f

	measure 'Tasa de reprogramacion' =
			DIVIDE(
			    [Citas Reprogramadas],
			    [Total de citas],
			    0
			)
		lineageTag: 4d08d653-6f69-4188-a97a-14a402d348ee

	measure 'Pacientes unicos' = DISTINCTCOUNT('citas_hechos'[id_paciente_sk])
		formatString: 0
		lineageTag: 2370f32e-e028-4db5-a462-f22b350fd0c3

	measure 'Medicos unicos' = DISTINCTCOUNT('citas_hechos'[id_medico_sk])
		formatString: 0
		lineageTag: 88e5d01d-dd9b-4f76-bdae-de7084178001

	measure 'Citas Promedio por Paciente' = DIVIDE([Total de citas], [Pacientes unicos], 0)
		lineageTag: 73dbc7a1-3fa1-4d59-ae7a-8b8a6e483d67

	measure 'Citas Promedio por Médico' = DIVIDE([Total de citas], [Medicos unicos], 0)
		lineageTag: b1b6d63e-6db0-4a70-a578-70bb5893cbce

	measure 'Citas Atendidas en Horas Pico' = CALCULATE([Citas Atendidas], FILTER('dim_tiempo', 'dim_tiempo'[hora] >= 9 && 'dim_tiempo'[hora] <= 17))
		formatString: 0
		lineageTag: bb7ef0fa-8c0a-463d-82a4-196161800eef

	column id_cita
		dataType: string
		lineageTag: df1d0691-62fa-4595-bed3-7ba6a8732d6f
		summarizeBy: none
		sourceColumn: id_cita

		annotation SummarizationSetBy = Automatic

	column id_paciente_sk
		dataType: string
		lineageTag: c1ea03a9-0492-40d8-b18d-e84bf8a47c6b
		summarizeBy: none
		sourceColumn: id_paciente_sk

		annotation SummarizationSetBy = Automatic

	column id_medico_sk
		dataType: string
		lineageTag: 58c74a79-bd7a-4a7f-b3e2-21403b4d0a35
		summarizeBy: none
		sourceColumn: id_medico_sk

		annotation SummarizationSetBy = Automatic

	column id_tiempo_sk
		dataType: string
		lineageTag: 72ed11ea-eb59-4a3e-bd80-400948dad77e
		summarizeBy: none
		sourceColumn: id_tiempo_sk

		annotation SummarizationSetBy = Automatic

	column fecha_hora_cita
		dataType: dateTime
		formatString: General Date
		lineageTag: 42b8c854-abe9-4ea4-8030-e59efee621a9
		summarizeBy: none
		sourceColumn: fecha_hora_cita

		variation Variación
			isDefault
			relationship: baed5e87-326b-42d8-b56e-bab069faaf82
			defaultHierarchy: LocalDateTable_88cd2777-d547-4459-943f-b2b14cea13ba.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column estado_cita
		dataType: string
		lineageTag: 124d50b2-82bb-4bc2-be9b-9895e3f1be14
		summarizeBy: none
		sourceColumn: estado_cita

		annotation SummarizationSetBy = Automatic

	column motivo_cita
		dataType: string
		lineageTag: 15f55fc3-4b5c-4083-8382-353b471f0ea6
		summarizeBy: none
		sourceColumn: motivo_cita

		annotation SummarizationSetBy = Automatic

	column fecha_carga
		dataType: dateTime
		formatString: General Date
		lineageTag: 63b80af1-f17a-469d-b05e-c2833f37438d
		summarizeBy: none
		sourceColumn: fecha_carga

		variation Variación
			isDefault
			relationship: 2408ebae-7ec1-4fca-8c01-0cf7dd40fc3e
			defaultHierarchy: LocalDateTable_183e3439-22cd-4387-901b-ced9da262d52.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	partition citas_hechos = m
		mode: import
		source =
				let
				    Origen = MySQL.Database("dborigen.mysql.database.azure.com", "db_destino", [ReturnSingleDatabase=true]),
				    db_destino_citas_hechos = Origen{[Schema="db_destino",Item="citas_hechos"]}[Data]
				in
				    db_destino_citas_hechos

